DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS companies CASCADE;
DROP TABLE IF EXISTS status CASCADE;
DROP TABLE IF EXISTS saraly_category CASCADE;
DROP TABLE IF EXISTS ofer CASCADE;
DROP TABLE IF EXISTS appry CASCADE;
DROP TABLE IF EXISTS message CASCADE;
